---
layout: post
lecture: 22
slides: chap11.pdf
---

Lecture {{ page.lecture }}
==========================

- [Slides](/pdf/{{ page.slides }})

**Class Code**

*ExceptionsDemo.java* demonstrates various *unchecked* runtime exceptions.
{% highlight java %}
public class ExceptionsDemo {

	public static void main(String[] args) {
		
		// division by zero causes ArithmeticException
		int result = 10/0;
		System.out.println("result = " + result);
		
		// the following code will throw ArrayIndexOutOfBoundsException
		String[] arrayOfStrings = { "hello", "world" };
		System.out.println(arrayOfStrings[2]);
		
		// the following code will throw NullPointerException
		String[] someArray = null;
		System.out.println(someArray.toString());		
	}
}
{% endhighlight %}

*DivideByZeroWithExceptionHandling.java* is an example of how to handle potential runtime exceptions.
{% highlight java %}
import java.util.InputMismatchException;
import java.util.Scanner;

public class DivideByZeroWithExceptionHandling
{
    // demonstrates throwing an exception when a divide-by-zero occurs
    public static int divide( int numerator, int denominator ) throws ArithmeticException
    {
        return numerator / denominator; // possible division by zero
    }

    public static void main( String args[] )
    {
        Scanner scanner = new Scanner( System.in ); // scanner for input
        boolean continueLoop = true; // determines if more input is needed

        while(continueLoop)
        {
            try // read two numbers and calculate quotient
            {
                System.out.print( "Please enter an integer numerator: " );
                int numerator = scanner.nextInt();
                
                System.out.print( "Please enter an integer denominator: " );
                int denominator = scanner.nextInt();

                int result = divide( numerator, denominator );
                
                System.out.printf( "\nResult: %d / %d = %d\n", numerator, denominator, result );
                
                continueLoop = false; // input successful; end looping
            }
            
            catch ( InputMismatchException inputMismatchException )
            {
                System.err.printf( "\nException: %s\n", inputMismatchException );
                
                scanner.nextLine(); // discard input so user can try again
                System.out.println("You must enter integers. Try again.\n");
            }
            
            catch ( ArithmeticException arithmeticException )
            {
                System.err.printf( "\nException: %s\n", arithmeticException );
                System.out.println("Zero is an invalid denominator. Try again.\n");
            }
            
        }
    }
}
{% endhighlight %}

*PrintWriterExample.java* shows an example where we have to deal with a *checked* exception, which
in this case is `java.io.FileNotFoundException`.
{% highlight java %}
import java.io.FileNotFoundException;
import java.io.PrintWriter;

public class PrintWriterExample {

	public static void main(String[] args) {
		
		try {
	        // open the file
		PrintWriter pw = new PrintWriter("hello.txt");
			
	        // write string to the file
	        pw.println("hello world!");

	        // need to flush the writer stream (close the file writer)
	        pw.close();
	        
		} catch (FileNotFoundException e) {
			System.err.println("Error: Could not open the file!");
		}
	}
}
{% endhighlight %}
